### ISSUE TITLE
如何运行？

### ISSUE THREAD

**Issue by ianGogh237** [atomicoo/EnhanceIMG#1]

**Comment by atomicoo** [comment]
@ianGogh237 你指的是哪个部分？如果是传统算法部分的话，[demo.py](https://github.com/atomicoo/EnhanceIMG/blob/main/demo.py) 里基本都有使用示例，GAN网络部分的话，[awegan/](https://github.com/atomicoo/EnhanceIMG/tree/main/awegan) 目录下的 simple_*.py 都是独立可以运行的程序。因为这个代码库的代码基本都是我平时没事瞎研究搞的，所以各部分代码其实没有很强的关联性，属于想到啥搞啥…………

**Comment by ianGogh237** [comment]
啊 谢谢，不过在VScode里还是会报错
